#' Spectral unmixing of cytometry files
#'
#'
#' This function performs the central task of spectral unmixing, to convert the
#' raw photon detector input to "biological" proxy-signals.
#' @importFrom BiocGenerics colnames
#' @importFrom flowCore exprs exprs<-
#' @param flowObj The fcs object to be filtered. Both flowFrames and flowSets
#' are accepted.
#' @param specMat This is a matrix generated by the secMatCalc function,
#' possibly with edited row names.
#' @return The unmixed data. It will be returned in the format it was imported
#' as.
#'
#' @examples
#' # Load uncompensated data
#' data(fullPanel)
#'
#' # Load the spectral unmixing matrix generated with controls from the same
#' # experiment. These can be generated using the specMatCalc function.
#' data(specMat)
#'
#' # And now, just run the function
#' fullPanelUnmix <- specUnmix(fullPanel, specMat)
#' @export specUnmix
specUnmix <- function(flowObj, specMat) {
    if (inherits(flowObj, "flowSet")) {
        resultObj <- fsApply(flowObj, specUnmixCoFunction,
            specMat = specMat
        )
    } else if (inherits(flowObj, "flowFrame")) {
        resultObj <- specUnmixCoFunction(flowObj, specMat = specMat)
    }
    return(resultObj)
}

specUnmixCoFunction <- function(focusFrame, specMat) {
    rawData <- exprs(focusFrame)[, colnames(specMat)]
    # Make the least squares fit based on the raw, uncompensated data.
    ls_corr <- lsfit(x = t(specMat), y = t(rawData), intercept = FALSE)
    # Export the unmixed portion of the least squares result.
    unmixResult <- t(ls_corr$coefficients)

    fullResult <- cbind(
        exprs(focusFrame)[, -which(colnames(focusFrame) %in%
            colnames(specMat))],
        unmixResult
    )
    fullResultFF <- focusFrame[, seq_len(ncol(fullResult))]
    BiocGenerics::colnames(fullResultFF) <- colnames(fullResult)
    exprs(fullResultFF) <- fullResult

    return(fullResultFF)
}
